#!/bin/sh -e

eyes() {
	case "$1" in
		0) echo ". ." ;;
		1) echo "· ·" ;;
		2) echo "^ ^" ;;
		3) echo "- -" ;;
		4) echo "~ ~" ;;
		5) echo "* *" ;;
		7) echo "-.-" ;;
		8) echo "~.~" ;;
		9) echo "*.*" ;;
		10) echo "0.0" ;;
		11) echo "0 0" ;;
		12) echo "o o" ;;
		13) echo "o.o" ;;
		14) echo "° o" ;;
		*) echo "^.^" ;;
	esac
}

display() {
	echo ""
	echo "   /'._           $c6$d$t  $distro"
	echo "  ($(eyes $1) 7          $c1$w$t  $wm"
	echo "   |'-'\"~.  .     $c3$k$t  $kern"
	echo "   Uu^~C_J._.\"    $c2$s$t  $shell"
	echo "                  $c5$r$t  $pkgs packages"
	echo ""
}

# ANSI colors helpers
for i in 0 1 2 3 4 5 6 7; do
	eval "c$i=\$(printf '%b' \"\\e[3${i}m\")"
done

d=$(printf '%b' "\e[1m") # make following text bold
t=$(printf '%b' "\e[0m") # end previously applied effects (colours, bold, etc.)
v=$(printf '%b' "\e[7m") # swap text and background colours

# Icons
d="󰻀" # distro (Linux logo)
w="♥" # window manager
k="" # kernel
s="󱆃" # shell
r="" # packages

# Info
wm=$(ps -e | grep -o "dwl" | head -n 1)
[ -z "$wm" ] && wm="Unknown WM"

kern=$(uname -r | cut -f1 -d '-')
shell=$SHELL

if type kiss >/dev/null 2>&1; then
	pkgs=$(kiss list | wc -l)
else
	pkgs="Unknown"
fi

distro="KISS Linux"

tput clear
display $1
