#!/bin/sh -e

eyes() {
	case "$1" in
		0) echo ". ." ;;
		1) echo "· ·" ;;
		2) echo "^ ^" ;;
		3) echo "- -" ;;
		4) echo "~ ~" ;;
		5) echo "* *" ;;
		7) echo "-.-" ;;
		8) echo "~.~" ;;
		9) echo "*.*" ;;
		10) echo "0.0" ;;
		11) echo "0 0" ;;
		12) echo "o o" ;;
		13) echo "o.o" ;;
		14) echo "° o" ;;
		*) echo "^.^" ;;
	esac
}

# It was necessary to use a file to store the
# color index. A global variable didn't work.
rainbow_file="/tmp/rainbow"

rb() {
	set -- 37 31 33 32 36 34 35 90

	rainbow_color=$(cat "$rainbow_file")

	[ $rainbow_color -gt $# ] && rainbow_color=1

	color=$(eval "echo \$$rainbow_color")

	rainbow_color=$(( rainbow_color + 1 ))
	echo "$rainbow_color" > "$rainbow_file"

	printf '\033[%sm' "$color"
}

display() {
	text="
$(rb)${d}♥ os$t       $f0│$t $distro
$(rb)${d}󱂬 wm$t       $f0│$t $wm
$(rb)${d}󱆃 shell$t    $f0│$t $shell
$(rb)${d} kernel$t   $f0│$t $kern
$(rb)${d} packages$t $f0│$t $pkgs
$(rb)${d}󰻠 cpu$t      $f0│$t $cpu
$(rb)${d}󰻠 gpu$t      $f0│$t $gpu
$(rb)${d}󰍛 memory$t   $f0│$t $mem_used of $mem used

$b0   $b1   $b2   $b3   $b4   $b5   $b6   $b7   $t
"

	cat="

 /'._
($(eyes 2) 7
 |'-'\"~.  .
 Uu^~C_J._.\"
"

	count1=$(printf '%s\n' "$cat" | wc -l)
	count2=$(printf '%s\n' "$text" | wc -l)

	max=$([ $count1 -gt $count2 ] && echo $count1 || echo $count2)

	i=1
	while [ $i -le $max ]; do
		line1=$(printf '%s\n' "$cat" | sed -n "${i}p")
		line2=$(printf '%s\n' "$text" | sed -n "${i}p")
		printf "    %-16s  %s\n" "$line1" "$line2"
		i=$(( i + 1 ))
	done
}

# ANSI colors helpers
for i in 0 1 2 3 4 5 6 7; do
	eval "c$i=\$(printf '%b' \"\\033[3${i}m\")"
done

for i in 0 1 2 3 4 5 6 7; do
	eval "e$i=\$(printf '%b' \"\\033[9${i}m\")"
done

for i in 0 1 2 3 4 5 6 7; do
	eval "b$i=\$(printf '%b' \"\\033[10${i}m\")"
done

d=$(printf '%b' "\033[1m")
e=$(printf '%b' "\033[2m")
t=$(printf '%b' "\033[0m")

# Info
wm=""

[ "$(ps -e | grep 'dwl')" != '' ] && wm="dwl"

distro=""
pm=""
pm_pkgs=""
bun_pkgs=""

if command -v kiss >/dev/null; then
	distro=$(printf "$d${c1}KISS $t")
	pm="kiss"
	pm_pkgs=$(kiss list | wc -l)
	echo "2" > "$rainbow_file"
elif command -v xbps-install >/dev/null; then
	distro="$(printf "$d${e7}VOID $t")"
	pm="xbps"
	pm_pkgs=$(xbps-query -l | wc -l)
	echo "1" > "$rainbow_file"
fi

pkgs="$pm_pkgs ($pm)"

if command -v bun >/dev/null; then
	bun_pkgs=$(bun pm ls -g | sed '1d' | wc -l)
	pkgs="$pkgs $bun_pkgs (bun)"
fi

kern=$(uname -r)
shell=$(basename $SHELL)

mem=$(free -h | grep 'Mem' | awk '{printf $2}')
mem_used=$(free -h | grep 'Mem' | awk '{printf $3}')

cpu=$(cat /proc/cpuinfo | grep -m1 'model name' | cut -d ':' -f2 | cut -d ' ' -f2-5)
gpu=$(vainfo 2>/dev/null | grep 'Driver version:' | awk -F' for ' '{print $2}' | awk '{print $1, $2, $3, $4}')

tput clear
display
