#!/bin/sh -e

eyes() {
	case "$1" in
		0) echo ". ." ;;
		1) echo "· ·" ;;
		2) echo "^ ^" ;;
		3) echo "- -" ;;
		4) echo "~ ~" ;;
		5) echo "* *" ;;
		7) echo "-.-" ;;
		8) echo "~.~" ;;
		9) echo "*.*" ;;
		10) echo "0.0" ;;
		11) echo "0 0" ;;
		12) echo "o o" ;;
		13) echo "o.o" ;;
		14) echo "° o" ;;
		*) echo "^.^" ;;
	esac
}

display() {
	text="
${c1}${d}♥ os$t       $f0│$t ${c1}KISS $t
${c3}${d}󱂬 wm$t       $f0│$t $wm
${c2}${d}󱆃 shell$t    $f0│$t $shell
${c4}${d} kernel$t   $f0│$t $kern
${c5}${d} packages$t $f0│$t $pkgs (kiss) $bun_pkgs (bun)

$b0   $b1   $b2   $b3   $b4   $b5   $b6   $b7   $t
"
# ${c6}${d}󰻠 cpu$t      $f0│$t $cpu
# ${c5}${d}󰍛 memory$t   $f0│$t $mem_used of $mem used

	cat="

 /'._
($(eyes $1) 7
 |'-'\"~.  .
 Uu^~C_J._.\"
"

	count1=$(printf '%s\n' "$cat" | wc -l)
	count2=$(printf '%s\n' "$text" | wc -l)

	max=$([ $count1 -gt $count2 ] && echo $count1 || echo $count2)

	i=1
	while [ $i -le $max ]; do
		line1=$(printf '%s\n' "$cat" | sed -n "${i}p")
		line2=$(printf '%s\n' "$text" | sed -n "${i}p")
		printf "    %-16s  %s\n" "$line1" "$line2"
		i=$(( i + 1 ))
	done
}

# ANSI colors helpers
for i in 0 1 2 3 4 5 6 7; do
	eval "c$i=\$(printf '%b' \"\\e[3${i}m\")"
done

for i in 0 1 2 3 4 5 6 7; do
	eval "f$i=\$(printf '%b' \"\\e[9${i}m\")"
done

for i in 0 1 2 3 4 5 6 7; do
	eval "b$i=\$(printf '%b' \"\\e[10${i}m\")"
done

d=$(printf '%b' "\e[1m")
e=$(printf '%b' "\e[2m")
t=$(printf '%b' "\e[0m")

# Info
wm=$(ps -e | grep -o "dwl" | head -n 1)
[ -z "$wm" ] && wm="Unknown WM"

pkgs=$(kiss list | wc -l)
bun_pkgs=$(bun pm ls -g | sed '1d' | wc -l)

distro="KISS Linux"
kern=$(uname -r)
shell='ash'

mem=$(free -h | grep 'Mem' | awk '{printf $2}')
mem_used=$(free -h | grep 'Mem' | awk '{printf $3}')

cpu=$(cat /proc/cpuinfo | grep -m1 "model name" | cut -d ':' -f2 | cut -d ' ' -f2-5)

tput clear
display $1
