#!/bin/sh -e

if [ "$1" == "start" ]; then
	sound() {
		pipewire > /tmp/pipewire.log 2>&1
		pipewire-pulse > /tmp/pipewire-pulse.log 2>&1
		sleep 1
		wireplumber > /tmp/wireplumber.log 2>&1
	}

	sound &
	wbg ~/Pics/Wallpapers/red-cape-cat-night.jpg &

	wlr-randr --output DVI-D-1 --mode 1920x1080

	/usr/libexec/xdg-desktop-portal > /tmp/xdg-desktop-portal.log 2>&1 &
	/usr/libexec/xdg-desktop-portal-wlr > /tmp/xdg-desktop-portal.log 2>&1 &

	exit
fi

export XCURSOR_THEME=BreezeX-Light
export XCURSOR_SIZE=24
export XCURSOR_PATH=$HOME/.icons

export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -pm 0700 $XDG_RUNTIME_DIR

exec dbus-run-session dwl -s "$0 start" > /tmp/dwl.log 2>&1
